---
steps:
  # - name: gcr.io/cloud-builders/curl
  #   id: download-berglas-bin
  #   args:
  #     - https://storage.googleapis.com/berglas/master/linux_amd64/berglas
  #     - --output
  #     - berglas
  # - name: ubuntu
  #   id: modify-bin-permission
  #   args:
  #     - chmod
  #     - "777"
  #     - berglas
  - name: gcr.io/cloud-builders/gcloud
    id: deploy-gae-app
    args:
      - app
      - deploy
      - appconfig.yaml